# Generated by Django 2.2.3 on 2019-07-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idautor', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Autor')),
                ('nomeautor', models.CharField(max_length=100, verbose_name='Nome')),
                ('biografia', models.TextField(verbose_name='Biografia')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('datanascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=500, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=50, null=True, verbose_name='Celular')),
                ('turno', models.CharField(max_length=50, null=True, verbose_name='Turno')),
                ('ano', models.IntegerField(null=True, verbose_name='Ano')),
                ('turma', models.CharField(max_length=20, null=True, verbose_name='Turma')),
                ('responsavel', models.TextField(null=True, verbose_name='Responsável pelos alunos')),
                ('perfil', models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno'), ('publico', 'Público')], max_length=15, verbose_name='Perfil')),
                ('user', models.CharField(max_length=20, verbose_name='Nome de Usuário')),
                ('senha', models.CharField(max_length=15, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Usuário')),
                ('nomeusuario', models.CharField(max_length=200, verbose_name='Nome')),
                ('datanascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=500, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=50, null=True, verbose_name='Celular')),
                ('perfil', models.CharField(choices=[('administrador', 'Administrador'), ('mediador', 'Mediador de Leitura')], max_length=15, verbose_name='Perfil')),
                ('username', models.CharField(max_length=20, verbose_name='Nome de Usuário')),
                ('password', models.CharField(max_length=15, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('idlivro', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Livro')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('capa', models.ImageField(null=True, upload_to='img/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('paginas', models.DecimalField(decimal_places=0, max_digits=7, null=True)),
                ('editora', models.CharField(max_length=200, verbose_name='Editora')),
                ('isbn', models.CharField(max_length=200, null=True, verbose_name='ISBN')),
                ('serie', models.CharField(max_length=200, null=True, verbose_name='Série')),
                ('tema', models.CharField(max_length=200, null=True)),
                ('faixaetaria', models.IntegerField(null=True, verbose_name='Faixa Etária')),
                ('sinopse', models.TextField(null=True, verbose_name='Sinópse')),
                ('ilustracao', models.CharField(max_length=200, null=True, verbose_name='Ilustração')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('disponivel', models.CharField(choices=[('S', 'Disponível'), ('N', 'Indisponível')], max_length=5, verbose_name='Disponível para Empréstimo')),
                ('idautor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaeulina.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('idemprestimo', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Empréstimo')),
                ('dataemprestimo', models.DateTimeField(auto_now_add=True)),
                ('datadevolucao', models.DateTimeField(verbose_name='Data de Devolução')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaeulina.Cliente')),
                ('idlivro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaeulina.Livro')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliotecaeulina.Usuario')),
            ],
        ),
    ]
