# Generated by Django 2.2.3 on 2020-04-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('nomeautor', models.CharField(max_length=100, verbose_name='Nome')),
                ('idautor', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('datanascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.TextField(blank=True, max_length=500, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('turno', models.CharField(blank=True, choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], max_length=50, null=True, verbose_name='Turno')),
                ('ano', models.IntegerField(blank=True, choices=[(1, '1º'), (1, '2º'), (1, '3º'), (1, '4º'), (1, '5º')], null=True, verbose_name='Ano')),
                ('turma', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20, null=True, verbose_name='Turma')),
                ('responsavel', models.TextField(blank=True, null=True, verbose_name='Responsável')),
                ('perfil', models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno'), ('publico', 'Público')], max_length=15, verbose_name='Perfil')),
                ('user', models.CharField(max_length=20, verbose_name='Nome de Usuário')),
                ('senha', models.CharField(max_length=15, verbose_name='Senha')),
                ('multa', models.IntegerField(default=0)),
                ('livrosemprestados', models.IntegerField(blank=True, default=0, verbose_name='Livros Emprestados')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nomeusuario', models.CharField(max_length=200, verbose_name='Nome')),
                ('datanascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(blank=True, max_length=500, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('perfil', models.CharField(choices=[('administrador', 'Administrador'), ('mediador', 'Mediador de Leitura')], max_length=15, verbose_name='Perfil')),
                ('username', models.CharField(max_length=20, verbose_name='Nome de Usuário')),
                ('password', models.CharField(max_length=15, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('idlivro', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('paginas', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('editora', models.CharField(blank=True, max_length=200, verbose_name='Editora')),
                ('isbn', models.CharField(blank=True, max_length=200, null=True, verbose_name='ISBN')),
                ('serie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Série')),
                ('tema', models.CharField(blank=True, max_length=200, null=True)),
                ('faixaetaria', models.IntegerField(blank=True, null=True, verbose_name='Faixa Etária')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinópse')),
                ('ilustracao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ilustração')),
                ('idautor', models.ManyToManyField(to='bibliotecaeulina.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('idexemplar', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('situacao', models.CharField(choices=[('Excelente', 'Excelente'), ('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Péssimo', 'Péssimo')], max_length=20, verbose_name='Situação')),
                ('status', models.BooleanField(choices=[(True, 'Disponível'), (False, 'Indisponível')], max_length=15, verbose_name='Disponível para Empréstimo')),
                ('idlivro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaeulina.Livro')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('idemprestimo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('dataemprestimo', models.DateTimeField(auto_now_add=True)),
                ('datadevolucao', models.DateTimeField(verbose_name='Data de Devolução')),
                ('datadevolvido', models.DateTimeField(blank=True, null=True, verbose_name='Data em que foi devolvido')),
                ('diasatrasados', models.IntegerField(default=0)),
                ('devolucao', models.BooleanField(default=False, verbose_name='Confirmar devolução')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaeulina.Cliente')),
                ('idexemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaeulina.Exemplar')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliotecaeulina.Usuario')),
            ],
        ),
    ]
