# Generated by Django 2.2.3 on 2020-04-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaeulina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('idcolecao', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome da Coleção')),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='idcolecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotecaeulina.Colecao'),
        ),
    ]
