# Generated by Django 2.2.3 on 2019-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaeulina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ano',
            field=models.IntegerField(choices=[('1', '1º'), ('2', '2º'), ('3', '3º'), ('4', '4º'), ('5', '5º')], null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='responsavel',
            field=models.TextField(null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='turno',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], max_length=50, null=True, verbose_name='Turno'),
        ),
    ]
