# Generated by Django 2.2.3 on 2020-04-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaeulina', '0002_auto_20200419_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='situacao',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Péssimo', 'Péssimo')], default='Excelente', max_length=20, verbose_name='Situação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='idcolecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotecaeulina.Colecao', verbose_name='Coleção'),
        ),
    ]
