# Generated by Django 2.2.3 on 2019-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaeulina', '0002_auto_20190727_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='turma',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20, null=True, verbose_name='Turma'),
        ),
    ]
