# Generated by Django 2.2.3 on 2019-07-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaeulina', '0003_auto_20190727_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ano',
            field=models.IntegerField(choices=[(1, '1º'), (1, '2º'), (1, '3º'), (1, '4º'), (1, '5º')], null=True, verbose_name='Ano'),
        ),
    ]
