# Generated by Django 2.2.3 on 2020-04-23 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaeulina', '0003_auto_20200419_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='idlivro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaeulina.Livro', verbose_name='Livro'),
        ),
    ]
