# Generated by Django 2.2.3 on 2019-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaeulina', '0004_auto_20190727_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(max_length=500, null=True, verbose_name='Endereço'),
        ),
    ]
